const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const AR_DIGITS='٠١٢٣٤٥٦٧٨٩';
const ar=n=>String(n).replace(/\d/g,d=>AR_DIGITS[d]);
const store={get(k,f=null){try{return JSON.parse(localStorage.getItem('hq:'+k))??f}catch{return f}},set(k,v){localStorage.setItem('hq:'+k,JSON.stringify(v))}};
const state={page:store.get('page',1),font:store.get('font',28),theme:store.get('theme','auto'),bookmarks:store.get('bookmarks',[]),query:'',surahFilter:'',audioRef:null,ayahs:[],ayahIndex:0,repeat:false,studio:{format:'square',style:'midnight',motion:'breathe',ref:null}};
let Q=null, M=null, deferredInstall=null, verseMap=new Map();
const audio=$('#audio');
const reciter=$('#reciter');
const toast=(msg)=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)};
const pageData=()=>Q.pages[state.page-1];
const uniqueAyahs=page=>{const a=[];for(const l of page.lines)for(const w of l.w)if(w.t&& !a.includes(w.r))a.push(w.r);return a};
function surah(id){return Q.surahs[id-1]||Q.surahs[0]}
function pageSurah(page){return surah(page.s||1)}
function saveProgress(ref){store.set('page',state.page);store.set('lastRef',ref||null);updateContinue()}
function updateContinue(){const s=surah(pageData()?.s||1);$('#continueMeta').textContent=`${s.name} · صفحة ${ar(state.page)}`;$('#lastReadText').textContent=`${s.name} · صفحة ${ar(state.page)}`}
function setTheme(t){state.theme=t;store.set('theme',t);document.body.classList.toggle('light',t==='light'||(t==='auto'&&matchMedia('(prefers-color-scheme:light)').matches));$$('#themeChoices button').forEach(b=>b.classList.toggle('active',b.dataset.theme===t))}
function setFont(n){state.font=Math.max(22,Math.min(38,n));store.set('font',state.font);document.documentElement.style.setProperty('--qfont',state.font+'px');$('#fontSizeValue').textContent=state.font}
function renderPage(){const p=pageData();if(!p)return;const s=surah(p.s);$('#pageNumber').textContent=ar(p.p);$('#pageCrumb').textContent=`صفحة ${ar(p.p)}`;$('#surahCrumb').textContent=s.name;$('#quranPage').innerHTML='';
 const head=document.createElement('div');head.className='page-header';head.innerHTML=`<span>${s.name}</span><span>${ar(p.p)}</span>`;$('#quranPage').append(head);
 const previous=Q.pages[p.p-2];
 const b=document.createElement('div');b.className='basmala';b.textContent='بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ'; if(p.p===1 || (p.s!==9 && (!previous || previous.s!==p.s))) $('#quranPage').append(b);
 for(const line of p.lines){const row=document.createElement('p');row.className='qline';let lastRef=null;for(const w of line.w){if(!w.t){if(w.e&&lastRef){const mark=document.createElement('span');mark.className='ayah-end';mark.textContent=ar(Number(lastRef.split(':')[1]));row.append(mark)}continue;}
   const span=document.createElement('span');span.className='word';span.textContent=w.t+' ';span.dataset.ref=w.r;span.title='اضغط للاستماع · ضغطتان للمعنى';span.addEventListener('click',e=>{if(e.detail===2)showMeaning(w.r);else playRef(w.r)});row.append(span);lastRef=w.r;
 }
 if(lastRef && !line.w.some(x=>x.e&&x.r===lastRef)){/* no marker */} $('#quranPage').append(row)}
 const foot=document.createElement('div');foot.className='page-footer';foot.textContent=`— ${ar(p.p)} —`;$('#quranPage').append(foot);
 state.ayahs=uniqueAyahs(p); state.ayahIndex=Math.max(0,state.ayahs.indexOf(state.audioRef)); saveProgress(state.audioRef); updateBookmarkButton(); updateStudioAyahs();
}
function gotoPage(n){n=Math.max(1,Math.min(604,n));state.page=n;stopAudio(false);renderPage();window.scrollTo({top:0,behavior:'smooth'})}
function openView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='search')$('#bigSearch').focus();if(v==='bookmarks')renderBookmarks();if(v==='studio')drawStudio();closeDrawer();}
function renderBookmarks(){const box=$('#bookmarksGrid');box.innerHTML='';if(!state.bookmarks.length){box.innerHTML='<div class="empty-state"><b>لا توجد علامات بعد</b><span>اضغط ◇ في شريط القراءة لحفظ الصفحة الحالية.</span></div>';return}for(const b of state.bookmarks){const card=document.createElement('div');card.className='bookmark-card';card.innerHTML=`<strong>${b.name}</strong><small>صفحة ${ar(b.page)}</small><p>${b.text||'صفحة محفوظة للعودة إليها'}</p>`;card.onclick=()=>gotoPage(b.page);box.append(card)}}
function addBookmark(){const p=pageData(),s=surah(p.s);const text=p.lines.flatMap(l=>l.w).filter(w=>w.t).slice(0,12).map(w=>w.t).join(' ');const idx=state.bookmarks.findIndex(x=>x.page===p.p);if(idx>=0){state.bookmarks.splice(idx,1);toast('أزيلت العلامة')}else{state.bookmarks.unshift({page:p.p,name:s.name,text});toast('حُفظت الصفحة')}store.set('bookmarks',state.bookmarks);updateBookmarkButton();renderBookmarks();updateSidebarBookmarks()}
function updateBookmarkButton(){$('#bookmarkPage').textContent=state.bookmarks.some(x=>x.page===state.page)?'◆':'◇';$('#bookmarkCount').textContent=state.bookmarks.length}
function updateSidebarBookmarks(){const box=$('#bookmarkList');box.innerHTML='';state.bookmarks.slice(0,5).forEach(b=>{const x=document.createElement('button');x.className='mini-bookmark';x.innerHTML=`<span>${b.name}</span><span>${ar(b.page)}</span>`;x.onclick=()=>gotoPage(b.page);box.append(x)})}
function openDrawer(){ $('#surahDrawer').classList.add('open');$('#backdrop').classList.add('open');renderSurahs() }
function closeDrawer(){ $('#surahDrawer').classList.remove('open');$('#backdrop').classList.remove('open') }
function renderSurahs(){const box=$('#surahList'),q=state.surahFilter.trim();box.innerHTML='';Q.surahs.filter(s=>!q||s.name.includes(q)||s.latin.toLowerCase().includes(q.toLowerCase())).forEach(s=>{const row=document.createElement('button');row.className='surah-row';row.innerHTML=`<span class="surah-no">${ar(s.id)}</span><div><strong>${s.name}</strong><small>${s.latin} · ${ar(s.ayahs)} آية</small></div><span>${ar(s.page||1)}</span>`;row.onclick=()=>{gotoPage(s.page||1);closeDrawer()};box.append(row)})}
function normalize(s){return s.normalize('NFKD').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ـ/g,'').toLowerCase()}
let flatWords=[];
function buildIndex(){flatWords=[];verseMap=new Map();for(const p of Q.pages)for(const l of p.lines)for(const w of l.w)if(w.t){flatWords.push({t:w.t,r:w.r,p:p.p,s:p.s});verseMap.set(w.r,`${verseMap.get(w.r)||''}${verseMap.has(w.r)?' ':''}${w.t}`)}}
function search(q){q=normalize(q);if(!q)return[];const seen=new Set(),out=[];for(const w of flatWords){if(normalize(w.t).includes(q)&&!seen.has(w.r)){seen.add(w.r);out.push(w);if(out.length>=80)break}}return out}
function renderSearch(q){const box=$('#searchResults');if(!q.trim()){box.innerHTML='<div class="empty-state"><b>ابدأ بكلمة</b><span>ستظهر النتائج هنا مع السورة ورقم الآية.</span></div>';return}const results=search(q);if(!results.length){box.innerHTML='<div class="empty-state"><b>لم نجد نتيجة</b><span>جرّب كلمة أقصر أو اكتبها بدون تشكيل.</span></div>';return}box.innerHTML='';for(const r of results){const card=document.createElement('div');card.className='search-result';card.innerHTML=`<div class="result-ref">${surah(r.s).name}<br>${ar(r.r.split(':')[1])}</div><div><div class="result-text">${verseText(r.r)}</div><div class="result-context">صفحة ${ar(r.p)}</div></div><div>›</div>`;card.onclick=()=>{gotoRef(r.r);openView('reader')};box.append(card)}}
function verseText(ref){return verseMap.get(ref)||''}
function gotoRef(ref){const p=Q.pages.find(p=>p.lines.some(l=>l.w.some(w=>w.r===ref)));if(p){state.page=p.p;state.audioRef=ref;renderPage();highlightRef(ref)}}
function highlightRef(ref){$$('.word').forEach(x=>x.classList.toggle('playing',x.dataset.ref===ref))}
function showMeaning(ref){const entries=M.entries[ref]||[];$('#meaningTitle').textContent=verseText(ref);$('#meaningRef').textContent=`${surah(Number(ref.split(':')[0])).name} · الآية ${ar(ref.split(':')[1])}`;const body=$('#meaningBody');body.innerHTML='';if(!entries.length){body.innerHTML='<div class="empty-state">لا توجد مادة معنى مسجلة لهذه الكلمة.</div>'}else entries.forEach(e=>{const book=M.books.find(b=>b.id===e.book);const d=document.createElement('div');d.className='meaning-entry';d.innerHTML=`<b>${e.phrase}</b><div class="meaning-book">${book?.n||'مصدر'}</div><p>${e.text}</p>`;body.append(d)});$('#meaningModal').classList.add('open')}
function audioUrl(ref){const [s,a]=ref.split(':').map(Number);return `https://everyayah.com/data/${reciter.value}/${String(s).padStart(3,'0')}${String(a).padStart(3,'0')}.mp3`}
function playRef(ref){const idx=state.ayahs.indexOf(ref);if(idx>=0)state.ayahIndex=idx;state.audioRef=ref;audio.src=audioUrl(ref);audio.play().catch(()=>toast('اضغط تشغيل مرة أخرى للسماح بالصوت'));highlightRef(ref);$('#audioState').textContent='جارٍ الاستماع';$('#audioLabel').textContent=`${surah(Number(ref.split(':')[0])).name} · آية ${ar(ref.split(':')[1])}`;$('#playBtn').textContent='Ⅱ';$('#mainPlay').textContent='Ⅱ';saveProgress(ref)}
function stopAudio(reset=true){audio.pause();if(reset)audio.currentTime=0;$('#playBtn').textContent='▶';$('#mainPlay').textContent='▶';$$('.word.playing').forEach(x=>x.classList.remove('playing'));$('#audioState').textContent='الاستماع متوقف'}
function playPause(){if(!audio.src){playRef(state.ayahs[0]||`${pageData().s}:1`);return}if(audio.paused){audio.play();$('#playBtn').textContent='Ⅱ';$('#mainPlay').textContent='Ⅱ';}else stopAudio(false)}
audio.addEventListener('loadedmetadata',()=>{$('#duration').textContent=time(audio.duration)});audio.addEventListener('timeupdate',()=>{$('#currentTime').textContent=time(audio.currentTime);$('#seek').value=audio.duration?audio.currentTime/audio.duration*100:0});audio.addEventListener('ended',()=>{if(state.repeat){playRef(state.audioRef);return}const next=state.ayahIndex+1;if(next<state.ayahs.length)playRef(state.ayahs[next]);else stopAudio(false)});reciter.addEventListener('change',()=>{if(state.audioRef)playRef(state.audioRef)});function time(x){if(!isFinite(x))return'0:00';return `${Math.floor(x/60)}:${String(Math.floor(x%60)).padStart(2,'0')}`}
function updateStudioAyahs(){const sel=$('#studioAyah');if(!sel)return;sel.innerHTML='';state.ayahs.forEach(r=>{const o=document.createElement('option');o.value=r;o.textContent=`${r} — ${verseText(r).slice(0,34)}`;sel.append(o)});if(state.studio.ref&&state.ayahs.includes(state.studio.ref))sel.value=state.studio.ref;else state.studio.ref=state.ayahs[0]}
function canvasSize(){return state.studio.format==='story'?[1080,1920]:state.studio.format==='wide'?[1920,1080]:[1080,1080]}
function drawStudio(){const c=$('#studioCanvas'),[w,h]=canvasSize();c.width=w;c.height=h;const x=c.getContext('2d'),style=state.studio.style;const bg={midnight:['#0b1110','#1e2b27','#c9a85b'],paper:['#f4ead2','#fffaf0','#5d4724'],dawn:['#402b33','#a8785e','#f6d8a2'],emerald:['#092a24','#0e5144','#d5c27c']}[style];const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,bg[0]);g.addColorStop(1,bg[1]);x.fillStyle=g;x.fillRect(0,0,w,h);x.globalAlpha=.12;x.beginPath();x.arc(w*.82,h*.18,w*.35,0,Math.PI*2);x.fillStyle=bg[2];x.fill();x.globalAlpha=1;x.textAlign='center';x.direction='rtl';x.fillStyle=bg[2];x.font=`700 ${Math.max(25,w/42)}px Cairo`;x.fillText('القرآن الكريم',w/2,h*.18);const ref=state.studio.ref||state.ayahs[0]||'1:1';const text=verseText(ref);x.fillStyle=style==='paper'?'#30281b':'#f7f2e8';const max=w*.78;let fs=Math.min(w/15,74);let lines=wrapCanvas(x,text,max,fs);while(lines.length>5){fs-=3;lines=wrapCanvas(x,text,max,fs)}x.font=`${fs}px Amiri`;const total=lines.length*fs*1.65;let y=(h-total)/2;lines.forEach(line=>{x.fillText(line,w/2,y);y+=fs*1.65});x.fillStyle=bg[2];x.font=`400 ${Math.max(18,w/70)}px Cairo`;x.fillText(`${surah(Number(ref.split(':')[0])).name}  ·  ${ar(ref.split(':')[1])}`,w/2,h*.83);x.globalAlpha=.5;x.font=`400 ${Math.max(14,w/90)}px Cairo`;x.fillText('المصحف · قراءة بطمأنينة',w/2,h*.9)}
function wrapCanvas(x,text,max,fs){x.font=`${fs}px Amiri`;const words=text.split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(x.measureText(test).width>max&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines}
async function exportPng(){drawStudio();const a=document.createElement('a');a.download='ayah-card.png';a.href=$('#studioCanvas').toDataURL('image/png');a.click();toast('تم تصدير البطاقة')}
async function exportVideo(){const c=$('#studioCanvas');if(!c.captureStream||!window.MediaRecorder){toast('تسجيل الفيديو غير مدعوم في هذا المتصفح');return}drawStudio();const stream=c.captureStream(30);const chunks=[];const mr=new MediaRecorder(stream,{mimeType:'video/webm'});mr.ondataavailable=e=>e.data.size&&chunks.push(e.data);mr.onstop=()=>{const blob=new Blob(chunks,{type:'video/webm'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ayah-motion.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('تم إنشاء الفيديو')};mr.start();const start=performance.now();function frame(t){const p=(t-start)/4500;if(p>=1){mr.stop();return}if(state.studio.motion!=='static'){drawStudio();const ctx=c.getContext('2d');ctx.save();ctx.globalAlpha=.08*Math.sin(p*Math.PI*4)+.1;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.restore()}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function init(){
 setTheme(state.theme);setFont(state.font);updateContinue();updateBookmarkButton();updateSidebarBookmarks();
 $('#prevPage').onclick=()=>gotoPage(state.page-1);$('#nextPage').onclick=()=>gotoPage(state.page+1);$('#bookmarkPage').onclick=addBookmark;$('#surahSelectBtn').onclick=openDrawer;$('#backdrop').onclick=closeDrawer;$$('[data-close]').forEach(b=>b.onclick=()=>{const id=b.dataset.close;$('#'+id)?.classList.remove('open');if(id==='surahDrawer')closeDrawer()});
 $('#fontMinus').onclick=()=>setFont(state.font-2);$('#fontPlus').onclick=()=>setFont(state.font+2);$('#settingsFontMinus').onclick=()=>setFont(state.font-2);$('#settingsFontPlus').onclick=()=>setFont(state.font+2);
 $('#settingsBtn').onclick=$('#settingsTop').onclick=()=>$('#settingsModal').classList.add('open');$('#themeBtn').onclick=()=>setTheme(document.body.classList.contains('light')?'dark':'light');$$('#themeChoices button').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));$('#clearProgress').onclick=()=>{store.set('page',1);store.set('lastRef',null);state.page=1;renderPage();toast('تمت إعادة الموضع')};
 $('#continueBtn').onclick=()=>gotoPage(state.page);$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open')};
 $$('[data-view]').forEach(b=>b.onclick=()=>openView(b.dataset.view));$('#searchTrigger').onclick=()=>openView('search');$('#bigSearch').oninput=e=>renderSearch(e.target.value);$('#clearSearch').onclick=()=>{$('#bigSearch').value='';renderSearch('');$('#bigSearch').focus()};$('#surahSearch').oninput=e=>{state.surahFilter=e.target.value;renderSurahs()};
 $('#playBtn').onclick=$('#mainPlay').onclick=playPause;$('#nextAyah').onclick=()=>{const n=state.ayahIndex+1;if(n<state.ayahs.length)playRef(state.ayahs[n])};$('#prevAyah').onclick=()=>{const n=state.ayahIndex-1;if(n>=0)playRef(state.ayahs[n])};$('#back10').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-10);$('#repeatBtn').onclick=()=>{state.repeat=!state.repeat;$('#repeatBtn').style.color=state.repeat?'var(--accent)':''};$('#seek').oninput=e=>{if(audio.duration)audio.currentTime=audio.duration*e.target.value/100};
 $$('#studioView .segmented button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.studio.format=b.dataset.format||state.studio.format;state.studio.motion=b.dataset.motion||state.studio.motion;drawStudio()});$$('.style-choice').forEach(b=>b.onclick=()=>{$$('.style-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.studio.style=b.dataset.style;drawStudio()});$('#studioAyah').onchange=e=>{state.studio.ref=e.target.value;drawStudio()};$('#exportPng').onclick=exportPng;$('#exportVideo').onclick=exportVideo;
 window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openView('search')}if(e.key==='ArrowLeft')gotoPage(state.page+1);if(e.key==='ArrowRight')gotoPage(state.page-1);if(e.key===' '&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();playPause()}});
 window.matchMedia('(prefers-color-scheme:light)').addEventListener?.('change',()=>state.theme==='auto'&&setTheme('auto'));
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false;$('#installBtn').classList.add('install-ready');$('#installBtn').onclick=async()=>{deferredInstall.prompt();deferredInstall=null}});
 renderPage();
}
async function boot(){try{const [q,m]=await Promise.all([fetch('data/quran.json').then(r=>r.json()),fetch('data/meanings.json').then(r=>r.json())]);Q=q;M=m;buildIndex();init();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}catch(e){document.body.innerHTML='<div style="padding:40px;font-family:sans-serif">تعذر تحميل بيانات المصحف. تأكد من تشغيله عبر GitHub Pages أو خادم HTTP.</div>';console.error(e)}}
boot();
